config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  resources :comments
  resources :posts

  root 'posts#index'
  get 'about_me' => 'posts#about_me'
  get 'destinations' => 'posts#destinations'
  get '/:name' => 'posts#user_posts', as: :user_posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user
	
	

	mount_uploaders :images, ImagesUploader
	serialize :images, JSON


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
  before_action :authenticate_user!, only: [:create]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def about_me
	end

	def destinations
	end

 protected

def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
	devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # before_action :authenticate_user!, only: [:new]


  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id, :user_id, :username)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    before_action :authenticate_user!, except: [:show, :index, :about_me, :destinations]

  

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def user_posts
    @user = User.find_by(username: params[:name])
  end

  def show
     @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
      

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :blog_entry, :user_id, :remove_image, {images:[]})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  
  <div class="form-group">
    <% if user_signed_in? %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <% end %>
    
  </div>

  <div class="form-group">
    <%= form.text_area :comment_entry, id: :comment_comment_entry, placeholder: "Talk to us!", class: "form-control"%>
  </div>

  <div class="field">
    <%= form.hidden_field :post_id, value: @post.id %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <li><%= link_to "New Post", new_post_path, class: "navbar-brand" %></li>
          <li><%= link_to "Destinations", destinations_path, class: "navbar-brand" %></li>
          <li><%= link_to "About Me", about_me_path, class: "navbar-brand" %></li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                
                @<%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, placeholder: "Blog Entry Title", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.text_area :blog_entry, placeholder: "Tell Us Something...", class: "form-control" %>
    <%= form.label :images %><br>
    <%= form.file_field :images, id: :post_images, multiple: true %><br>
    
    <% @post.images.each do |image| %>
      <%= image_tag image.url %>
    <% end %>
  </div>



  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/about_me.html.erb
<center><h1>About Me</h1></center>

	<div class="row">
		
		<div class="col-md-10 col-md-offset-1">

			<center><img src="https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/14993567_125632667918161_7823185261947995875_n.jpg?oh=1af68adc6a408fde7daf6bc5ebd8cc7a&oe=5AA8B774"><center>

			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
			<center><img src="https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-1/p320x320/14915561_106215109859917_2868840995762579739_n.jpg?oh=6dbcfcb13256ebf14396cd27ad305cf3&oe=5A64A90B"><center>

			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

			<h1>My Neverending Bucket List</h1>
			<br>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas efficitur tincidunt odio, ut pharetra lorem pharetra ac. Vestibulum interdum leo enim, lacinia auctor quam pellentesque vel. Aenean interdum ex sed lectus dictum rhoncus. Nullam dignissim facilisis velit, non lobortis tortor sagittis vel. Aenean sit amet malesuada dolor. Suspendisse facilisis id ligula ac pharetra. Pellentesque et iaculis ex. Mauris sodales viverra lectus id varius. Praesent dictum, massa nec feugiat interdum, enim tortor efficitur orci, quis gravida ex massa fringilla eros. Ut volutpat, neque id porta eleifend, mi nunc vehicula elit, malesuada mattis ex ex a massa. Fusce sollicitudin maximus nibh, vitae semper enim. Morbi molestie tortor sed fermentum placerat. Integer gravida, sem ac pellentesque rhoncus, magna turpis cursus nulla, non dignissim metus quam eget purus. Duis aliquam fringilla lacus id tempus. Vestibulum iaculis maximus massa quis pretium. Fusce vulputate at lacus sed facilisis.


			Aliquam ullamcorper enim ut libero suscipit dignissim. Curabitur ac velit mattis, sodales arcu a, mollis lorem. Quisque consectetur ut leo sed convallis. Praesent lectus magna, pretium vitae posuere ut, gravida non enim. Vestibulum malesuada diam quis nunc maximus sagittis. Pellentesque semper mi non nisi mattis eleifend vitae ac risus. Maecenas nec rutrum ipsum. Morbi massa lectus, tempor ut vestibulum vel, bibendum non neque. Praesent mattis pharetra ante vitae congue. Sed sagittis elementum tortor, vitae venenatis odio lacinia eu. Sed ultrices elementum odio ac eleifend. Pellentesque iaculis tincidunt lectus, non hendrerit eros dapibus ac. Quisque sit amet pharetra urna, sit amet ullamcorper justo.

			Ut volutpat, risus in pharetra tristique, dui dui mattis sem, in efficitur sapien orci nec nisi. Nullam sed ullamcorper nulla. Donec faucibus nibh nec molestie pretium. Etiam at arcu nec nisi pretium pretium eu id augue. Proin rhoncus at augue vel ultrices. Quisque elementum eros eu nulla tincidunt condimentum. Nulla facilisi. Proin efficitur ipsum quis ligula tempor, ut sollicitudin enim laoreet. Nulla vitae eros metus. Maecenas fermentum lobortis volutpat. Cras hendrerit, quam at dapibus sollicitudin, sem quam malesuada odio, id placerat orci mi in urna. Fusce sagittis, metus sagittis finibus suscipit, odio odio bibendum sem, quis consectetur nibh sem a odio. Quisque semper ullamcorper ullamcorper.</p>
			
			<img src="https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/14993447_125628727918555_4563758477195323975_n.jpg?oh=7efdf1c6b53cfd0dbd213f1fe8a4a97c&oe=5A9BB1C3">

			<h1>Why I Started This Blog</h1>		
			<p>Aliquam ullamcorper enim ut libero suscipit dignissim. Curabitur ac velit mattis, sodales arcu a, mollis lorem. Quisque consectetur ut leo sed convallis. Praesent lectus magna, pretium vitae posuere ut, gravida non enim. Vestibulum malesuada diam quis nunc maximus sagittis. Pellentesque semper mi non nisi mattis eleifend vitae ac risus. Maecenas nec rutrum ipsum. Morbi massa lectus, tempor ut vestibulum vel, bibendum non neque. Praesent mattis pharetra ante vitae congue. Sed sagittis elementum tortor, vitae venenatis odio lacinia eu. Sed ultrices elementum odio ac eleifend. Pellentesque iaculis tincidunt lectus, non hendrerit eros dapibus ac. Quisque sit amet pharetra urna, sit amet ullamcorper justo.</p>




			


		</div>
	</div>
	

app/views/posts/destinations.html.erb
<center><h1>Destinations</h1></center>

<h3 style="text-align: center;" align="justify">
<em>I haven’t been everywhere… but it’s on my list.<br>
-Susan Sontag</em>
</h3>
<br />
<br />

<center>

<script src="https://www.amcharts.com/lib/3/ammap.js" type="text/javascript"></script>
<script src="https://www.amcharts.com/lib/3/maps/js/worldHigh.js" type="text/javascript"></script>
<script src="https://www.amcharts.com/lib/3/themes/dark.js" type="text/javascript"></script>
<div id="mapdiv" style="width: 1000px; height: 650px;"></div>
<div style="width: 1000px; font-size: 70%; padding: 5px 0; text-align: center; background-color: #535364; margin-top: 1px; color: #B4B4B7;"><a href="https://www.amcharts.com/visited_countries/" style="color: #B4B4B7; style="color: #B4B4B7;"></a>.</div>
<script type="text/javascript">
var map = AmCharts.makeChart("mapdiv",{
type: "map",
theme: "dark",
projection: "mercator",
panEventsEnabled : true,
backgroundColor : "#535364",
backgroundAlpha : 1,
zoomControl: {
zoomControlEnabled : true
},
dataProvider : {
map : "worldHigh",
getAreasFromMap : true,
areas :
[
	{
		"id": "AT",
		"showAsSelected": true
	},
	{
		"id": "BE",
		"showAsSelected": true
	},
	{
		"id": "CZ",
		"showAsSelected": true
	},
	{
		"id": "DK",
		"showAsSelected": true
	},
	{
		"id": "EE",
		"showAsSelected": true
	},
	{
		"id": "FI",
		"showAsSelected": true
	},
	{
		"id": "FR",
		"showAsSelected": true
	},
	{
		"id": "DE",
		"showAsSelected": true
	},
	{
		"id": "GR",
		"showAsSelected": true
	},
	{
		"id": "HU",
		"showAsSelected": true
	},
	{
		"id": "IE",
		"showAsSelected": true
	},
	{
		"id": "IT",
		"showAsSelected": true
	},
	{
		"id": "LU",
		"showAsSelected": true
	},
	{
		"id": "MC",
		"showAsSelected": true
	},
	{
		"id": "NL",
		"showAsSelected": true
	},
	{
		"id": "PT",
		"showAsSelected": true
	},
	{
		"id": "RU",
		"showAsSelected": true
	},
	{
		"id": "ES",
		"showAsSelected": true
	},
	{
		"id": "SE",
		"showAsSelected": true
	},
	{
		"id": "TR",
		"showAsSelected": true
	},
	{
		"id": "GB",
		"showAsSelected": true
	},
	{
		"id": "VA",
		"showAsSelected": true
	},
	{
		"id": "AW",
		"showAsSelected": true
	},
	{
		"id": "BS",
		"showAsSelected": true
	},
	{
		"id": "BZ",
		"showAsSelected": true
	},
	{
		"id": "VG",
		"showAsSelected": true
	},
	{
		"id": "CA",
		"showAsSelected": true
	},
	{
		"id": "KY",
		"showAsSelected": true
	},
	{
		"id": "CR",
		"showAsSelected": true
	},
	{
		"id": "MX",
		"showAsSelected": true
	},
	{
		"id": "PR",
		"showAsSelected": true
	},
	{
		"id": "MF",
		"showAsSelected": true
	},
	{
		"id": "SX",
		"showAsSelected": true
	},
	{
		"id": "TC",
		"showAsSelected": true
	},
	{
		"id": "US",
		"showAsSelected": true
	},
	{
		"id": "VI",
		"showAsSelected": true
	},
	{
		"id": "AU",
		"showAsSelected": true
	},
	{
		"id": "NZ",
		"showAsSelected": true
	}
]
},
areasSettings : {
autoZoom : true,
color : "#B4B4B7",
colorSolid : "#84ADE9",
selectedColor : "#84ADE9",
outlineColor : "#666666",
rollOverColor : "#9EC2F7",
rollOverOutlineColor : "#000000"
}
});
</script>
</center>

<p>
<p>
<p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<header class="header" role="banner">
  <center>
    <img src="https://mykidlovesbroccoli.files.wordpress.com/2015/03/where-to-next-sign.jpg" width="1100" height="425">
  </center>
  </header>

<p>
  
</p>

    <div class="container">
    <!-- <div class="pull-right"> -->
        <div class="row">
          <div class="col-sm-12">
          <center>
            <div id="my-slider" class="carousel slide" data-ride="carousel">
                <!-- indicators dot nov -->
                <ol class="carousel-indicators">
                  <li data-target="#my-slider" data-slide-to="0" class="active"></li>
                  <li data-target="#my-slider" data-slide-to="1"></li>
                  <li data-target="#my-slider" data-slide-to="2"></li>
                  <li data-target="#my-slider" data-slide-to="3"></li>
                  <li data-target="#my-slider" data-slide-to="4"></li>
                  <li data-target="#my-slider" data-slide-to="5"></li>
                  <li data-target="#my-slider" data-slide-to="6"></li>
                </ol>

                <!-- wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                  <div class="item active">
                      <img src="https://siroccoverland.files.wordpress.com/2014/02/otways-6.jpg?w=1484&h=834"/>
                      <div class="carousel-caption">
                      <h4>Australia</h4>
                      </div>
                  </div>

                  <div class="item">
                      <img src="https://media.cntraveler.com/photos/592462096af5d360c3ac77bc/master/w_1024,c_limit/GettyImages-93299393.jpg"/>
                      <div class="carousel-caption">
                      <h4>France</h4>
                      </div>
                  </div>

                  <div class="item">
                      <img src="http://static1.squarespace.com/static/55c48e13e4b09e7cf2404af2/56d9b0e4b6aa60744e4321db/56d9ddb860b5e99884df0142/1457118962499/?format=1000w"/>
                      <div class="carousel-caption">
                      <h4>Russia</h4>
                      </div>
                  </div>

                  <div class="item">
                      <img src="https://www.airtransat.com/getmedia/a3652ee2-5b50-4b17-b35d-d76f5d2862b3/Costa-Rica01.jpg?width=980.jpg"/>
                      <div class="carousel-caption">
                      <h4>Costa Rica</h4>
                      </div>
                  </div>

                  <div class="item">
                      <img src="https://fthmb.tqn.com/1x_5avTe_KqV6wkXZ6ZIygsqRcQ=/960x0/filters:no_upscale()/88786323-56a3b0fc5f9b58b7d0d331f2.jpg"/>
                      <div class="carousel-caption">
                      <h4>Greece</h4>
                      </div>
                  </div>

                  <div class="item">
                      <img src="http://ichef.bbci.co.uk/wwfeatures/wm/live/1280_640/images/live/p0/1f/fy/p01ffyz3.jpg"/>
                      <div class="carousel-caption">
                      <h4>Turkey</h4>
                      </div>
                  </div>

                  <div class="item">
                      <img src="https://az616578.vo.msecnd.net/files/2016/06/18/636018720314907846447253188_florence,%20italy.jpg"/>
                      <div class="carousel-caption">
                      <h4>Italy</h4>
                      </div>
                  </div>

                <!-- controls or next and prev buttons -->
                  <a class="left carousel-control" href="#my-slider" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                  </a>

                  <a class="right carousel-control" href="#my-slider" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                  </a>
                </div>
            </div>
            </center>
          </div>
        </div>
      </div>
<br />
<br />
<!-- <h1>Posts</h1> -->

<div class="row">
    <% @posts.each do |post| %>

      <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
          
          <div class="panel-heading">
            <h4><%= link_to post.title, post %></h4>
            <p><%= link_to post.user.username, user_posts_path(name: post.user.username)  %><em> Published at: <%= post.created_at.strftime('%d %b %Y at %I:%M %p') %></em></p></p>
          </div>
          <div class="panel-body">
            <% post.images.each do |image| %>
            <%= image_tag image.url %>
            <% end %>
            <%= post.blog_entry[0..100] %> (<%= link_to "Read More", post %>)
          </div>
          <div class="panel-footer">
            <% if user_signed_in? %>
            <%= link_to 'Edit', edit_post_path(post), class: "btn btn-info" %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %> 

</div>

<strong><%= link_to "Home", root_path%></strong>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
	<div class="panel-heading">
		<p class="panel-title"><%= @post.title %></p>
		<%= @post.user.username %> <em> Published at: <%= @post.created_at.strftime('%d %b %Y at %I:%M %p') %></em>
	</div>

	<div class="panel-body">
		
		<h4><%= @post.user.username %></h4>
		 <% @post.images.each do |image| %>
		 	<%= image_tag image.url %>
		 <% end %>
		<%= @post.blog_entry %>
	</div>

	
	<div class="panel-footer">
		<% if user_signed_in? %>
		<button class="btn btn-warning"><%= link_to 'Edit', edit_post_path(@post) %></button>
		<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div id="comments">
			<%= render'comments/form', comment: @comment %>
			<% @post.comments.each do |comment| %>
				<div class="well"
					<p><strong><%= comment.user.username %></strong> said: <br/>
					</strong> said at <%= comment.created_at.strftime('%d %b %Y at %I:%M %p') %>:</p>
					<p><%= comment.comment_entry %></p>
				</div>
			<% end %>
		</div>
	</div>
</div>